server:
  port: 8082
  servlet:
    context-path: /odi

spring:
  application:
    name: odi

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
    health:
      show-details: always

info:
  application:
    name:   odi
    server:
      port: 8082
      servlet:
        context-path: /odi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
    enabled: true