server:
  port: 8762
#  servlet:
#     context-path: /cricket-registry

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false


management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
    health:
      show-details: always

info:
  application:
    name: "eureka-cricket-registry"
    description: "eureka-registry-for-cricket-app"
    clients:
      client1: "Test-cricket"
      client2: "ODI-cricket"

